- name: Job 1001-1001-1001 | Set timezone to {{ default_timezone }}
  community.general.timezone:
    name: "{{ default_timezone }}"
#
- name: Job 1001-1001-1001 | Set locales
  community.general.locale_gen:
    name:
      - en_GB.UTF-8
      - en_GB.UTF-8 UTF-8
    state: present
  check_mode: on
#


# timezone:
#   name:  # not required. Name of the timezone for the system clock. Default is to keep current setting. B(At least one of name and hwclock are required.)
#   hwclock: local # not required. choices: local;UTC. Whether the hardware clock is in UTC or in local timezone. 
#   Default is to keep current setting. Note that this option is recommended not to change and may fail to configure, 
#   especially on virtual environments such as AWS. B(At least one of name and hwclock are required.) I(Only used on Linux.)