hostname_additional_hosts:
  - ip_address: 192.168.14.254
    hostname: virthost01.skyline.lan
    hostname_short: virthost01
  - ip_address: 192.168.77.254
    hostname: virthost01.skyline.lan
    hostname_short: virthost01
  - ip_address: 192.168.8.254
    hostname: virthost01.skyline.lan
    hostname_short: virthost01
  - ip_address: 192.168.14.254
    hostname: sawadogo.xyz
    hostname_short: virthost01
  #
#virthost01.skyline.lan: 
ansible_connection: local # this will overwrite any other type of connections. its needed here.
ansible_become_pass: '{{ localhost_become_pass }}'
#
### PRVS | CONFIG ###
prvs_copy_home: no                       # Copy default user's home files in place
prvs_root_passwd: no                     # update root passward
#
dkr_copy_def_files: no                   # Copy default docker files to target server
#
crntb_activate_cronjobs: no
#
#
### APT | PACKAGES INSTALL ###
instl_def_pckg: yes                       # Install complete packages. A 'no' will remove it from the host (apt_def_pckg_lst)
instl_utl_pckg: yes                        # Install complete packages. A 'no' will remove it from the host (apt_util_lst)
sysd_strt_srvc: yes                       # Start services
instl_ansbl_pckg: yes                      # Install ansible using PIP (pip_ansbl_pckg_lst apt_ansbl_pckg_lst)
instl_docker_pckg: yes                    # Install Docker package (apt_docker_pckg_lst)
apt_host_pckg_lst:                        # Install Host Specific Packages (keep this empty. use host_var to overwrite it)
  - cifs-utils
  
pip_host_pckg_lst:                        # Install Host Specific PIP Packages when ansible is also installed
#- azure
- azure.cli
- azure.mgmt.network
- azure.storage.blob
- azure.mgmt.automation
- azure-mgmt-compute #(https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
- azure-mgmt-storage #(https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
- azure-mgmt-resource #(https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
- azure-keyvault-secrets #(https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault
- azure-storage-blob #(https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts
- azure.mgmt.recoveryservicesbackup
- pip-review
- 'ansible[azure]'
#
#
# docker containers
dckr_dpl_pihole: no
dckr_dpl_iSpy: no
dckr_dpl_semaphore: yes
dckr_dpl_trcmmnd: yes